version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - deployment/secrets/postgres.dev.env

  web:
    build: .
    command: /usr/src/app/deployment/app/docker_entrypoint.dev.sh
    env_file:
      - deployment/secrets/invertimo.dev.env
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db