version: "3.9"

services:
  db:
    image: postgres

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always

  redis:
    image: redis:alpine

  celery:
    build: .
    command: /usr/src/venv/bin/celery -A invertimo worker -l info
    depends_on:
      - db
      - redis
    restart: always

  celery-beat:
    build: .
    command: /usr/src/venv/bin/celery -A invertimo beat -l info
    depends_on:
      - db
      - redis
    restart: always