version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/postgres_prod:/var/lib/postgresql/data
    env_file:
      - deployment/secrets/postgres.prod.env

  redis:
    volumes:
      - ./data/redis_prod:/data

  web:
    env_file:
      - deployment/secrets/invertimo.prod.env
    volumes:
      - /var/www/invertimo.com/static:/var/www/invertimo.com/static/
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    env_file:
      - deployment/secrets/invertimo.prod.env
    volumes:
      - .:/usr/src/app
  celery-beat:
    env_file:
      - deployment/secrets/invertimo.prod.env
    volumes:
      - .:/usr/src/app