version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/postgres_staging:/var/lib/postgresql/data
    env_file:
      - deployment/secrets/postgres.staging.env

  web:
    env_file:
      - deployment/secrets/invertimo.staging.env
    volumes:
      - .:/usr/src/app
      - /var/www/staging.invertimo.com/static:/var/www/staging.invertimo.com/static/
    ports:
      - "8000:8000"
    depends_on:
      - db