# Generated by Django 3.2 on 2021-04-18 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(1, 'EUR'), (2, 'GBP'), (3, 'USD')], default=1)),
                ('nickname', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='finance.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('transaction_costs', models.DecimalField(decimal_places=5, max_digits=12)),
                ('local_value', models.DecimalField(decimal_places=5, max_digits=12)),
                ('value_in_account_currency', models.DecimalField(decimal_places=5, max_digits=12)),
                ('order_id', models.CharField(max_length=200, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.position')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('currency', models.IntegerField(choices=[(1, 'EUR'), (2, 'GBP'), (3, 'USD')], default=3)),
                ('country', models.CharField(max_length=200, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='finance.exchange')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='finance.security'),
        ),
        migrations.CreateModel(
            name='ExchangeIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.IntegerField(choices=[(1, 'CODE'), (2, 'MIC'), (3, 'SEGMENT MIC')])),
                ('value', models.CharField(max_length=20)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='finance.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='finance.account')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='finance.position')),
            ],
        ),
    ]
