# Generated by Django 3.2 on 2021-05-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_transaction_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
