# Generated by Django 3.2 on 2021-05-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_position_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='position',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_in_account_currency',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
