# Generated by Django 3.2 on 2021-05-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20210503_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
    ]
