# Generated by Django 3.2 on 2021-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
