# Generated by Django 3.2 on 2021-05-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_account_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.IntegerField(choices=[(1, 'EUR'), (2, 'GBP'), (3, 'USD'), (4, 'GBX')])),
                ('to_currency', models.IntegerField(choices=[(1, 'EUR'), (2, 'GBP'), (3, 'USD'), (4, 'GBX')])),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=12)),
                ('date', models.DateField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.security')),
            ],
        ),
    ]
