# Generated by Django 3.2 on 2021-05-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_currencyexchangerate_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyexchangerate',
            name='value',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=12),
            preserve_default=False,
        ),
    ]
