# Generated by Django 3.2 on 2021-05-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_currencyexchangerate_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyexchangerate',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-executed_at']},
        ),
    ]
