# Generated by Django 3.2 on 2021-08-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_transaction_order_id'),
    ]

    operations = [
        migrations.RenameModel('Security', 'Asset'),
        migrations.RenameField('PriceHistory', 'security', 'asset'),
        migrations.RenameField('Position', 'security', 'asset'),
    ]
