# Generated by Django 3.2 on 2021-08-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_auto_20210822_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
    ]
