# Generated by Django 3.2 on 2021-08-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20210822_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='finance.exchange'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set(),
        ),
    ]
