# Generated by Django 3.2 on 2021-10-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_auto_20211028_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='sell_date',
            field=models.DateField(null=True),
        ),
    ]
