# Generated by Django 3.2 on 2021-12-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_auto_20211102_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.IntegerField(choices=[(1, 'DEGIRO')])),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Partial success'), (3, 'Failure')])),
            ],
        ),
        migrations.CreateModel(
            name='TransactionImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_record', models.TextField()),
                ('created_new', models.BooleanField(default=False)),
                ('successful', models.BooleanField(default=True)),
                ('issue_type', models.IntegerField(choices=[(1, 'UNKNOWN_FAILURE'), (2, 'SOLD_BEFORE_BOUGHT'), (3, 'BAD_FORMAT')], null=True)),
                ('raw_issue', models.TextField(null=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_records', to='finance.transaction')),
                ('transaction_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='finance.transactionimport')),
            ],
        ),
    ]
