# Generated by Django 3.2 on 2022-01-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_transactionimport_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionimport',
            name='integration',
            field=models.IntegerField(choices=[(1, 'DEGIRO'), (2, 'BINANCE_CSV')]),
        ),
    ]
