# Generated by Django 3.2 on 2022-01-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_alter_transactionimport_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.IntegerField(choices=[(1, 'Stock'), (2, 'Bond'), (3, 'Fund'), (4, 'Crypto')], default=1),
        ),
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'GBP'), (3, 'USD'), (4, 'GBX')], null=True),
        ),
    ]
