# Generated by Django 3.2 on 2022-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_auto_20220121_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
