# Generated by Django 3.2 on 2022-01-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_alter_transaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='local_value',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_in_account_currency',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_costs',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value_in_account_currency',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
    ]
