# Generated by Django 3.2 on 2022-01-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_auto_20220122_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountevent',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='finance.transaction'),
        ),
        migrations.AlterField(
            model_name='accountevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'DEPOSIT'), (2, 'WITHDRAWAL'), (3, 'DIVIDEND'), (4, 'SAVINGS_INTEREST'), (5, 'STAKING_INTEREST')]),
        ),
    ]
