# Generated by Django 3.2 on 2022-01-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_auto_20220129_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_record', models.TextField()),
                ('created_new', models.BooleanField(default=False)),
                ('successful', models.BooleanField(default=True)),
                ('issue_type', models.IntegerField(choices=[(1, 'UNKNOWN_FAILURE'), (2, 'SOLD_BEFORE_BOUGHT'), (3, 'BAD_FORMAT')], null=True)),
                ('raw_issue', models.TextField(null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_records', to='finance.transaction')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_transaction_records', to='finance.transaction')),
                ('transaction_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_records', to='finance.transactionimport')),
            ],
        ),
    ]
