# Generated by Django 3.2 on 2022-01-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_auto_20220130_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionimport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=17),
        ),
    ]
