# Generated by Django 3.2 on 2022-02-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0036_auto_20220202_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimportrecord',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_records', to='finance.transaction'),
        ),
    ]
