# Generated by Django 3.2 on 2022-02-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_auto_20220203_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='isin',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
