# Generated by Django 3.2 on 2022-04-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0039_auto_20220226_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'GBP'), (3, 'USD'), (4, 'GBX'), (5, 'HKD'), (6, 'SGD'), (7, 'JPY'), (8, 'CAD'), (9, 'PLN')], default=1),
        ),
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'GBP'), (3, 'USD'), (4, 'GBX'), (5, 'HKD'), (6, 'SGD'), (7, 'JPY'), (8, 'CAD'), (9, 'PLN')], null=True),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='from_currency',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'GBP'), (3, 'USD'), (4, 'GBX'), (5, 'HKD'), (6, 'SGD'), (7, 'JPY'), (8, 'CAD'), (9, 'PLN')]),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='to_currency',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'GBP'), (3, 'USD'), (4, 'GBX'), (5, 'HKD'), (6, 'SGD'), (7, 'JPY'), (8, 'CAD'), (9, 'PLN')]),
        ),
    ]
